name: ci

# Default to 'contents: read', which grants actions to read commits.
#
# If any permission is set, any permission not included in the list is
# implicitly set to "none".
#
# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    strategy:
      matrix:
        go: ["1.13", "oldstable", "stable"]

    steps:
      - uses: actions/checkout@v4 
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Create go.mod
        run: |
          ln -s vendor.mod go.mod
          ln -s vendor.sum go.sum
      - name: Run tests
        run: go test -race
